'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Ce code source a été automatiquement généré par Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace X3WebReferenceV6
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="CAdxWebServiceXmlCCSoapBinding", [Namespace]:="http://www.adonix.com/WSS"),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(CAdxParamKeyValue)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(CAdxMessage))>  _
    Partial Public Class CAdxWebServiceXmlCCService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private runOperationCompleted As System.Threading.SendOrPostCallback
        
        Private readOperationCompleted As System.Threading.SendOrPostCallback
        
        Private deleteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private saveOperationCompleted As System.Threading.SendOrPostCallback
        
        Private queryOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getDescriptionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getDataXmlSchemaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private modifyOperationCompleted As System.Threading.SendOrPostCallback
        
        Private actionObjectKeysOperationCompleted As System.Threading.SendOrPostCallback
        
        Private actionObjectOperationCompleted As System.Threading.SendOrPostCallback
        
        Private insertLinesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private deleteLinesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.SFAO.My.MySettings.Default.SFAO_X3WebReferenceV6_CAdxWebServiceXmlCCService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event runCompleted As runCompletedEventHandler
        
        '''<remarks/>
        Public Event readCompleted As readCompletedEventHandler
        
        '''<remarks/>
        Public Event deleteCompleted As deleteCompletedEventHandler
        
        '''<remarks/>
        Public Event saveCompleted As saveCompletedEventHandler
        
        '''<remarks/>
        Public Event queryCompleted As queryCompletedEventHandler
        
        '''<remarks/>
        Public Event getDescriptionCompleted As getDescriptionCompletedEventHandler
        
        '''<remarks/>
        Public Event getDataXmlSchemaCompleted As getDataXmlSchemaCompletedEventHandler
        
        '''<remarks/>
        Public Event modifyCompleted As modifyCompletedEventHandler
        
        '''<remarks/>
        Public Event actionObjectKeysCompleted As actionObjectKeysCompletedEventHandler
        
        '''<remarks/>
        Public Event actionObjectCompleted As actionObjectCompletedEventHandler
        
        '''<remarks/>
        Public Event insertLinesCompleted As insertLinesCompletedEventHandler
        
        '''<remarks/>
        Public Event deleteLinesCompleted As deleteLinesCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://www.adonix.com/WSS", ResponseNamespace:="http://www.adonix.com/WSS")>  _
        Public Function run(ByVal callContext As CAdxCallContext, ByVal publicName As String, ByVal inputXml As String) As <System.Xml.Serialization.SoapElementAttribute("runReturn")> CAdxResultXml
            Dim results() As Object = Me.Invoke("run", New Object() {callContext, publicName, inputXml})
            Return CType(results(0),CAdxResultXml)
        End Function
        
        '''<remarks/>
        Public Overloads Sub runAsync(ByVal callContext As CAdxCallContext, ByVal publicName As String, ByVal inputXml As String)
            Me.runAsync(callContext, publicName, inputXml, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub runAsync(ByVal callContext As CAdxCallContext, ByVal publicName As String, ByVal inputXml As String, ByVal userState As Object)
            If (Me.runOperationCompleted Is Nothing) Then
                Me.runOperationCompleted = AddressOf Me.OnrunOperationCompleted
            End If
            Me.InvokeAsync("run", New Object() {callContext, publicName, inputXml}, Me.runOperationCompleted, userState)
        End Sub
        
        Private Sub OnrunOperationCompleted(ByVal arg As Object)
            If (Not (Me.runCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent runCompleted(Me, New runCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://www.adonix.com/WSS", ResponseNamespace:="http://www.adonix.com/WSS")>  _
        Public Function read(ByVal callContext As CAdxCallContext, ByVal publicName As String, ByVal objectKeys() As CAdxParamKeyValue) As <System.Xml.Serialization.SoapElementAttribute("readReturn")> CAdxResultXml
            Dim results() As Object = Me.Invoke("read", New Object() {callContext, publicName, objectKeys})
            Return CType(results(0),CAdxResultXml)
        End Function
        
        '''<remarks/>
        Public Overloads Sub readAsync(ByVal callContext As CAdxCallContext, ByVal publicName As String, ByVal objectKeys() As CAdxParamKeyValue)
            Me.readAsync(callContext, publicName, objectKeys, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub readAsync(ByVal callContext As CAdxCallContext, ByVal publicName As String, ByVal objectKeys() As CAdxParamKeyValue, ByVal userState As Object)
            If (Me.readOperationCompleted Is Nothing) Then
                Me.readOperationCompleted = AddressOf Me.OnreadOperationCompleted
            End If
            Me.InvokeAsync("read", New Object() {callContext, publicName, objectKeys}, Me.readOperationCompleted, userState)
        End Sub
        
        Private Sub OnreadOperationCompleted(ByVal arg As Object)
            If (Not (Me.readCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent readCompleted(Me, New readCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://www.adonix.com/WSS", ResponseNamespace:="http://www.adonix.com/WSS")>  _
        Public Function delete(ByVal callContext As CAdxCallContext, ByVal publicName As String, ByVal objectKeys() As CAdxParamKeyValue) As <System.Xml.Serialization.SoapElementAttribute("deleteReturn")> CAdxResultXml
            Dim results() As Object = Me.Invoke("delete", New Object() {callContext, publicName, objectKeys})
            Return CType(results(0),CAdxResultXml)
        End Function
        
        '''<remarks/>
        Public Overloads Sub deleteAsync(ByVal callContext As CAdxCallContext, ByVal publicName As String, ByVal objectKeys() As CAdxParamKeyValue)
            Me.deleteAsync(callContext, publicName, objectKeys, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub deleteAsync(ByVal callContext As CAdxCallContext, ByVal publicName As String, ByVal objectKeys() As CAdxParamKeyValue, ByVal userState As Object)
            If (Me.deleteOperationCompleted Is Nothing) Then
                Me.deleteOperationCompleted = AddressOf Me.OndeleteOperationCompleted
            End If
            Me.InvokeAsync("delete", New Object() {callContext, publicName, objectKeys}, Me.deleteOperationCompleted, userState)
        End Sub
        
        Private Sub OndeleteOperationCompleted(ByVal arg As Object)
            If (Not (Me.deleteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent deleteCompleted(Me, New deleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://www.adonix.com/WSS", ResponseNamespace:="http://www.adonix.com/WSS")>  _
        Public Function save(ByVal callContext As CAdxCallContext, ByVal publicName As String, ByVal objectXml As String) As <System.Xml.Serialization.SoapElementAttribute("saveReturn")> CAdxResultXml
            Dim results() As Object = Me.Invoke("save", New Object() {callContext, publicName, objectXml})
            Return CType(results(0),CAdxResultXml)
        End Function
        
        '''<remarks/>
        Public Overloads Sub saveAsync(ByVal callContext As CAdxCallContext, ByVal publicName As String, ByVal objectXml As String)
            Me.saveAsync(callContext, publicName, objectXml, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub saveAsync(ByVal callContext As CAdxCallContext, ByVal publicName As String, ByVal objectXml As String, ByVal userState As Object)
            If (Me.saveOperationCompleted Is Nothing) Then
                Me.saveOperationCompleted = AddressOf Me.OnsaveOperationCompleted
            End If
            Me.InvokeAsync("save", New Object() {callContext, publicName, objectXml}, Me.saveOperationCompleted, userState)
        End Sub
        
        Private Sub OnsaveOperationCompleted(ByVal arg As Object)
            If (Not (Me.saveCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent saveCompleted(Me, New saveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://www.adonix.com/WSS", ResponseNamespace:="http://www.adonix.com/WSS")>  _
        Public Function query(ByVal callContext As CAdxCallContext, ByVal publicName As String, ByVal objectKeys() As CAdxParamKeyValue, ByVal listSize As Integer) As <System.Xml.Serialization.SoapElementAttribute("queryReturn")> CAdxResultXml
            Dim results() As Object = Me.Invoke("query", New Object() {callContext, publicName, objectKeys, listSize})
            Return CType(results(0),CAdxResultXml)
        End Function
        
        '''<remarks/>
        Public Overloads Sub queryAsync(ByVal callContext As CAdxCallContext, ByVal publicName As String, ByVal objectKeys() As CAdxParamKeyValue, ByVal listSize As Integer)
            Me.queryAsync(callContext, publicName, objectKeys, listSize, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub queryAsync(ByVal callContext As CAdxCallContext, ByVal publicName As String, ByVal objectKeys() As CAdxParamKeyValue, ByVal listSize As Integer, ByVal userState As Object)
            If (Me.queryOperationCompleted Is Nothing) Then
                Me.queryOperationCompleted = AddressOf Me.OnqueryOperationCompleted
            End If
            Me.InvokeAsync("query", New Object() {callContext, publicName, objectKeys, listSize}, Me.queryOperationCompleted, userState)
        End Sub
        
        Private Sub OnqueryOperationCompleted(ByVal arg As Object)
            If (Not (Me.queryCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent queryCompleted(Me, New queryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://www.adonix.com/WSS", ResponseNamespace:="http://www.adonix.com/WSS")>  _
        Public Function getDescription(ByVal callContext As CAdxCallContext, ByVal publicName As String) As <System.Xml.Serialization.SoapElementAttribute("getDescriptionReturn")> CAdxResultXml
            Dim results() As Object = Me.Invoke("getDescription", New Object() {callContext, publicName})
            Return CType(results(0),CAdxResultXml)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getDescriptionAsync(ByVal callContext As CAdxCallContext, ByVal publicName As String)
            Me.getDescriptionAsync(callContext, publicName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getDescriptionAsync(ByVal callContext As CAdxCallContext, ByVal publicName As String, ByVal userState As Object)
            If (Me.getDescriptionOperationCompleted Is Nothing) Then
                Me.getDescriptionOperationCompleted = AddressOf Me.OngetDescriptionOperationCompleted
            End If
            Me.InvokeAsync("getDescription", New Object() {callContext, publicName}, Me.getDescriptionOperationCompleted, userState)
        End Sub
        
        Private Sub OngetDescriptionOperationCompleted(ByVal arg As Object)
            If (Not (Me.getDescriptionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getDescriptionCompleted(Me, New getDescriptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://www.adonix.com/WSS", ResponseNamespace:="http://www.adonix.com/WSS")>  _
        Public Function getDataXmlSchema(ByVal callContext As CAdxCallContext, ByVal publicName As String) As <System.Xml.Serialization.SoapElementAttribute("getDataXmlSchemaReturn")> CAdxResultXml
            Dim results() As Object = Me.Invoke("getDataXmlSchema", New Object() {callContext, publicName})
            Return CType(results(0),CAdxResultXml)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getDataXmlSchemaAsync(ByVal callContext As CAdxCallContext, ByVal publicName As String)
            Me.getDataXmlSchemaAsync(callContext, publicName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getDataXmlSchemaAsync(ByVal callContext As CAdxCallContext, ByVal publicName As String, ByVal userState As Object)
            If (Me.getDataXmlSchemaOperationCompleted Is Nothing) Then
                Me.getDataXmlSchemaOperationCompleted = AddressOf Me.OngetDataXmlSchemaOperationCompleted
            End If
            Me.InvokeAsync("getDataXmlSchema", New Object() {callContext, publicName}, Me.getDataXmlSchemaOperationCompleted, userState)
        End Sub
        
        Private Sub OngetDataXmlSchemaOperationCompleted(ByVal arg As Object)
            If (Not (Me.getDataXmlSchemaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getDataXmlSchemaCompleted(Me, New getDataXmlSchemaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://www.adonix.com/WSS", ResponseNamespace:="http://www.adonix.com/WSS")>  _
        Public Function modify(ByVal callContext As CAdxCallContext, ByVal publicName As String, ByVal objectKeys() As CAdxParamKeyValue, ByVal objectXml As String) As <System.Xml.Serialization.SoapElementAttribute("modifyReturn")> CAdxResultXml
            Dim results() As Object = Me.Invoke("modify", New Object() {callContext, publicName, objectKeys, objectXml})
            Return CType(results(0),CAdxResultXml)
        End Function
        
        '''<remarks/>
        Public Overloads Sub modifyAsync(ByVal callContext As CAdxCallContext, ByVal publicName As String, ByVal objectKeys() As CAdxParamKeyValue, ByVal objectXml As String)
            Me.modifyAsync(callContext, publicName, objectKeys, objectXml, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub modifyAsync(ByVal callContext As CAdxCallContext, ByVal publicName As String, ByVal objectKeys() As CAdxParamKeyValue, ByVal objectXml As String, ByVal userState As Object)
            If (Me.modifyOperationCompleted Is Nothing) Then
                Me.modifyOperationCompleted = AddressOf Me.OnmodifyOperationCompleted
            End If
            Me.InvokeAsync("modify", New Object() {callContext, publicName, objectKeys, objectXml}, Me.modifyOperationCompleted, userState)
        End Sub
        
        Private Sub OnmodifyOperationCompleted(ByVal arg As Object)
            If (Not (Me.modifyCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent modifyCompleted(Me, New modifyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://www.adonix.com/WSS", ResponseNamespace:="http://www.adonix.com/WSS")>  _
        Public Function actionObjectKeys(ByVal callContext As CAdxCallContext, ByVal publicName As String, ByVal actionCode As String, ByVal objectKeys() As CAdxParamKeyValue) As <System.Xml.Serialization.SoapElementAttribute("actionObjectKeysReturn")> CAdxResultXml
            Dim results() As Object = Me.Invoke("actionObjectKeys", New Object() {callContext, publicName, actionCode, objectKeys})
            Return CType(results(0),CAdxResultXml)
        End Function
        
        '''<remarks/>
        Public Overloads Sub actionObjectKeysAsync(ByVal callContext As CAdxCallContext, ByVal publicName As String, ByVal actionCode As String, ByVal objectKeys() As CAdxParamKeyValue)
            Me.actionObjectKeysAsync(callContext, publicName, actionCode, objectKeys, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub actionObjectKeysAsync(ByVal callContext As CAdxCallContext, ByVal publicName As String, ByVal actionCode As String, ByVal objectKeys() As CAdxParamKeyValue, ByVal userState As Object)
            If (Me.actionObjectKeysOperationCompleted Is Nothing) Then
                Me.actionObjectKeysOperationCompleted = AddressOf Me.OnactionObjectKeysOperationCompleted
            End If
            Me.InvokeAsync("actionObjectKeys", New Object() {callContext, publicName, actionCode, objectKeys}, Me.actionObjectKeysOperationCompleted, userState)
        End Sub
        
        Private Sub OnactionObjectKeysOperationCompleted(ByVal arg As Object)
            If (Not (Me.actionObjectKeysCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent actionObjectKeysCompleted(Me, New actionObjectKeysCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://www.adonix.com/WSS", ResponseNamespace:="http://www.adonix.com/WSS")>  _
        Public Function actionObject(ByVal callContext As CAdxCallContext, ByVal publicName As String, ByVal actionCode As String, ByVal objectXml As String) As <System.Xml.Serialization.SoapElementAttribute("actionObjectReturn")> CAdxResultXml
            Dim results() As Object = Me.Invoke("actionObject", New Object() {callContext, publicName, actionCode, objectXml})
            Return CType(results(0),CAdxResultXml)
        End Function
        
        '''<remarks/>
        Public Overloads Sub actionObjectAsync(ByVal callContext As CAdxCallContext, ByVal publicName As String, ByVal actionCode As String, ByVal objectXml As String)
            Me.actionObjectAsync(callContext, publicName, actionCode, objectXml, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub actionObjectAsync(ByVal callContext As CAdxCallContext, ByVal publicName As String, ByVal actionCode As String, ByVal objectXml As String, ByVal userState As Object)
            If (Me.actionObjectOperationCompleted Is Nothing) Then
                Me.actionObjectOperationCompleted = AddressOf Me.OnactionObjectOperationCompleted
            End If
            Me.InvokeAsync("actionObject", New Object() {callContext, publicName, actionCode, objectXml}, Me.actionObjectOperationCompleted, userState)
        End Sub
        
        Private Sub OnactionObjectOperationCompleted(ByVal arg As Object)
            If (Not (Me.actionObjectCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent actionObjectCompleted(Me, New actionObjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://www.adonix.com/WSS", ResponseNamespace:="http://www.adonix.com/WSS")>  _
        Public Function insertLines(ByVal callContext As CAdxCallContext, ByVal publicName As String, ByVal objectKeys() As CAdxParamKeyValue, ByVal blocKey As String, ByVal lineKey As String, ByVal lineXml As String) As <System.Xml.Serialization.SoapElementAttribute("insertLinesReturn")> CAdxResultXml
            Dim results() As Object = Me.Invoke("insertLines", New Object() {callContext, publicName, objectKeys, blocKey, lineKey, lineXml})
            Return CType(results(0),CAdxResultXml)
        End Function
        
        '''<remarks/>
        Public Overloads Sub insertLinesAsync(ByVal callContext As CAdxCallContext, ByVal publicName As String, ByVal objectKeys() As CAdxParamKeyValue, ByVal blocKey As String, ByVal lineKey As String, ByVal lineXml As String)
            Me.insertLinesAsync(callContext, publicName, objectKeys, blocKey, lineKey, lineXml, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub insertLinesAsync(ByVal callContext As CAdxCallContext, ByVal publicName As String, ByVal objectKeys() As CAdxParamKeyValue, ByVal blocKey As String, ByVal lineKey As String, ByVal lineXml As String, ByVal userState As Object)
            If (Me.insertLinesOperationCompleted Is Nothing) Then
                Me.insertLinesOperationCompleted = AddressOf Me.OninsertLinesOperationCompleted
            End If
            Me.InvokeAsync("insertLines", New Object() {callContext, publicName, objectKeys, blocKey, lineKey, lineXml}, Me.insertLinesOperationCompleted, userState)
        End Sub
        
        Private Sub OninsertLinesOperationCompleted(ByVal arg As Object)
            If (Not (Me.insertLinesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent insertLinesCompleted(Me, New insertLinesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://www.adonix.com/WSS", ResponseNamespace:="http://www.adonix.com/WSS")>  _
        Public Function deleteLines(ByVal callContext As CAdxCallContext, ByVal publicName As String, ByVal objectKeys() As CAdxParamKeyValue, ByVal blocKey As String, ByVal lineKeys() As String) As <System.Xml.Serialization.SoapElementAttribute("deleteLinesReturn")> CAdxResultXml
            Dim results() As Object = Me.Invoke("deleteLines", New Object() {callContext, publicName, objectKeys, blocKey, lineKeys})
            Return CType(results(0),CAdxResultXml)
        End Function
        
        '''<remarks/>
        Public Overloads Sub deleteLinesAsync(ByVal callContext As CAdxCallContext, ByVal publicName As String, ByVal objectKeys() As CAdxParamKeyValue, ByVal blocKey As String, ByVal lineKeys() As String)
            Me.deleteLinesAsync(callContext, publicName, objectKeys, blocKey, lineKeys, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub deleteLinesAsync(ByVal callContext As CAdxCallContext, ByVal publicName As String, ByVal objectKeys() As CAdxParamKeyValue, ByVal blocKey As String, ByVal lineKeys() As String, ByVal userState As Object)
            If (Me.deleteLinesOperationCompleted Is Nothing) Then
                Me.deleteLinesOperationCompleted = AddressOf Me.OndeleteLinesOperationCompleted
            End If
            Me.InvokeAsync("deleteLines", New Object() {callContext, publicName, objectKeys, blocKey, lineKeys}, Me.deleteLinesOperationCompleted, userState)
        End Sub
        
        Private Sub OndeleteLinesOperationCompleted(ByVal arg As Object)
            If (Not (Me.deleteLinesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent deleteLinesCompleted(Me, New deleteLinesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://www.adonix.com/WSS")>  _
    Partial Public Class CAdxCallContext
        
        Private codeLangField As String
        
        Private codeUserField As String
        
        Private passwordField As String
        
        Private poolAliasField As String
        
        Private poolIdField As String
        
        Private requestConfigField As String
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property codeLang() As String
            Get
                Return Me.codeLangField
            End Get
            Set
                Me.codeLangField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property codeUser() As String
            Get
                Return Me.codeUserField
            End Get
            Set
                Me.codeUserField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property poolAlias() As String
            Get
                Return Me.poolAliasField
            End Get
            Set
                Me.poolAliasField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property poolId() As String
            Get
                Return Me.poolIdField
            End Get
            Set
                Me.poolIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property requestConfig() As String
            Get
                Return Me.requestConfigField
            End Get
            Set
                Me.requestConfigField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://www.adonix.com/WSS")>  _
    Partial Public Class CAdxParamKeyValue
        
        Private keyField As String
        
        Private valueField As String
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property key() As String
            Get
                Return Me.keyField
            End Get
            Set
                Me.keyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://www.adonix.com/WSS")>  _
    Partial Public Class CAdxTechnicalInfos
        
        Private busyField As Boolean
        
        Private changeLanguageField As Boolean
        
        Private changeUserIdField As Boolean
        
        Private flushAdxField As Boolean
        
        Private loadWebsDurationField As Double
        
        Private nbDistributionCycleField As Integer
        
        Private poolDistribDurationField As Double
        
        Private poolEntryIdxField As Integer
        
        Private poolExecDurationField As Double
        
        Private poolRequestDurationField As Double
        
        Private poolWaitDurationField As Double
        
        Private processReportField As String
        
        Private processReportSizeField As Integer
        
        Private reloadWebsField As Boolean
        
        Private resumitAfterDBOpenField As Boolean
        
        Private rowInDistribStackField As Integer
        
        Private totalDurationField As Double
        
        Private traceRequestField As String
        
        Private traceRequestSizeField As Integer
        
        '''<remarks/>
        Public Property busy() As Boolean
            Get
                Return Me.busyField
            End Get
            Set
                Me.busyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property changeLanguage() As Boolean
            Get
                Return Me.changeLanguageField
            End Get
            Set
                Me.changeLanguageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property changeUserId() As Boolean
            Get
                Return Me.changeUserIdField
            End Get
            Set
                Me.changeUserIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property flushAdx() As Boolean
            Get
                Return Me.flushAdxField
            End Get
            Set
                Me.flushAdxField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property loadWebsDuration() As Double
            Get
                Return Me.loadWebsDurationField
            End Get
            Set
                Me.loadWebsDurationField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property nbDistributionCycle() As Integer
            Get
                Return Me.nbDistributionCycleField
            End Get
            Set
                Me.nbDistributionCycleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property poolDistribDuration() As Double
            Get
                Return Me.poolDistribDurationField
            End Get
            Set
                Me.poolDistribDurationField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property poolEntryIdx() As Integer
            Get
                Return Me.poolEntryIdxField
            End Get
            Set
                Me.poolEntryIdxField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property poolExecDuration() As Double
            Get
                Return Me.poolExecDurationField
            End Get
            Set
                Me.poolExecDurationField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property poolRequestDuration() As Double
            Get
                Return Me.poolRequestDurationField
            End Get
            Set
                Me.poolRequestDurationField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property poolWaitDuration() As Double
            Get
                Return Me.poolWaitDurationField
            End Get
            Set
                Me.poolWaitDurationField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property processReport() As String
            Get
                Return Me.processReportField
            End Get
            Set
                Me.processReportField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property processReportSize() As Integer
            Get
                Return Me.processReportSizeField
            End Get
            Set
                Me.processReportSizeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property reloadWebs() As Boolean
            Get
                Return Me.reloadWebsField
            End Get
            Set
                Me.reloadWebsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property resumitAfterDBOpen() As Boolean
            Get
                Return Me.resumitAfterDBOpenField
            End Get
            Set
                Me.resumitAfterDBOpenField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property rowInDistribStack() As Integer
            Get
                Return Me.rowInDistribStackField
            End Get
            Set
                Me.rowInDistribStackField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property totalDuration() As Double
            Get
                Return Me.totalDurationField
            End Get
            Set
                Me.totalDurationField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property traceRequest() As String
            Get
                Return Me.traceRequestField
            End Get
            Set
                Me.traceRequestField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property traceRequestSize() As Integer
            Get
                Return Me.traceRequestSizeField
            End Get
            Set
                Me.traceRequestSizeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://www.adonix.com/WSS")>  _
    Partial Public Class CAdxMessage
        
        Private messageField As String
        
        Private typeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property type() As String
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://www.adonix.com/WSS")>  _
    Partial Public Class CAdxResultXml
        
        Private messagesField() As CAdxMessage
        
        Private resultXmlField As String
        
        Private statusField As Integer
        
        Private technicalInfosField As CAdxTechnicalInfos
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property messages() As CAdxMessage()
            Get
                Return Me.messagesField
            End Get
            Set
                Me.messagesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property resultXml() As String
            Get
                Return Me.resultXmlField
            End Get
            Set
                Me.resultXmlField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property status() As Integer
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(IsNullable:=true)>  _
        Public Property technicalInfos() As CAdxTechnicalInfos
            Get
                Return Me.technicalInfosField
            End Get
            Set
                Me.technicalInfosField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub runCompletedEventHandler(ByVal sender As Object, ByVal e As runCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class runCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CAdxResultXml
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CAdxResultXml)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub readCompletedEventHandler(ByVal sender As Object, ByVal e As readCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class readCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CAdxResultXml
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CAdxResultXml)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub deleteCompletedEventHandler(ByVal sender As Object, ByVal e As deleteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class deleteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CAdxResultXml
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CAdxResultXml)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub saveCompletedEventHandler(ByVal sender As Object, ByVal e As saveCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class saveCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CAdxResultXml
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CAdxResultXml)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub queryCompletedEventHandler(ByVal sender As Object, ByVal e As queryCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class queryCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CAdxResultXml
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CAdxResultXml)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub getDescriptionCompletedEventHandler(ByVal sender As Object, ByVal e As getDescriptionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getDescriptionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CAdxResultXml
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CAdxResultXml)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub getDataXmlSchemaCompletedEventHandler(ByVal sender As Object, ByVal e As getDataXmlSchemaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getDataXmlSchemaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CAdxResultXml
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CAdxResultXml)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub modifyCompletedEventHandler(ByVal sender As Object, ByVal e As modifyCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class modifyCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CAdxResultXml
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CAdxResultXml)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub actionObjectKeysCompletedEventHandler(ByVal sender As Object, ByVal e As actionObjectKeysCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class actionObjectKeysCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CAdxResultXml
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CAdxResultXml)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub actionObjectCompletedEventHandler(ByVal sender As Object, ByVal e As actionObjectCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class actionObjectCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CAdxResultXml
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CAdxResultXml)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub insertLinesCompletedEventHandler(ByVal sender As Object, ByVal e As insertLinesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class insertLinesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CAdxResultXml
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CAdxResultXml)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub deleteLinesCompletedEventHandler(ByVal sender As Object, ByVal e As deleteLinesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class deleteLinesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CAdxResultXml
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CAdxResultXml)
            End Get
        End Property
    End Class
End Namespace
